# Generated by Django 5.1.6 on 2025-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='professor',
        ),
        migrations.AddField(
            model_name='module',
            name='professor',
            field=models.ManyToManyField(to='ratings.professor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='professor',
            field=models.ManyToManyField(to='ratings.professor'),
        ),
    ]
